config/routes.rb
Opac::Application.routes.draw do

  resources :signups

  resources :plans
  
  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'

  get "stock/show"

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}
  resources :authentications

  match '/auth/failure' => 'Ibtrs#index'

  match 'ibtrs/search' => 'ibtrs#search'
  resources :titles, :authors, :ibtrs, :branch, :stock, :stockitems
  
  match 'statistics/:title_id' => 'statistics#view'
  

  

  root :to => "Dashboard#show"

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def show
    if params[:current_branch].blank?
      user_session['current_branch'] = Branch.branch_from_subdomain(current_user.subdomain)
    else
      user_session['current_branch'] = Branch.find(params[:current_branch].to_i)
    end
    @associate_branches = Branch.associate_branches(current_user.subdomain)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/show.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$('#current_branch').html('<%= user_session['current_branch'].name %>');
<% end -%>

<div class='notice'>
	You are a staff of <b><%= Branch.branch_name_from_subdomain(current_user.subdomain) %>.</b>
	If this is not correct, call tech support.
	<br/>
	You are currently logged into <%= user_session['current_branch'].name %>. 
		
	<% if !current_user.strata_employee? && @associate_branches.length > 1 -%>
		<hr/>
		Click on any of the following branches to change your current branch.
		<br/>
		<ol>
			<% @associate_branches.each do |b| -%>
				<li><%= link_to b.name, dashboard_path(:current_branch => b.id), :confirm => "Are you sure you want to change the branch to #{b.name}?" %></li>
			<% end -%>
		</ol>
	<% end -%>		
</div>

<% if current_user.frontoffice? -%>
<div class='alert'>
	You logged in with <%= current_user.email %>, instead use the id that was created for you.
</div>
<% end -%>


	<div class='span-24'>
		<% if current_user.strata_employee? %>
			<div class='span-24'>
				<div class='span-2 menu-button menu-color'>
					<div class='menu-icon'>
						<%= link_to ibtrs_path do -%>
							<%= image_tag 'IBT.png' %>
						<% end -%>
					</div>
					<div class='span-1 menu-text'>
						IBT
					</div>
				</div>
			</div>
		<% end -%>
		<div class='span-24' style='height:10px'>
		</div>
		<div class='span-24'>	
			<div class='span-1 menu-button menu-color'>
				<div class='menu-icon'>
					<%= link_to :controller => 'plans', :action => 'index', :signUpMonths => 1 do -%>
						<%= image_tag 'SignUp.png' %>
					<% end -%>
				</div>
				<div class='span-1 menu-text'>
					New Member
				</div>
			</div>
		</div>
	</div>