config/routes.rb
Opac::Application.routes.draw do

  resources :signups

  resources :plans
  
  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'

  get "stock/show"

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}
  resources :authentications

  match '/auth/failure' => 'Ibtrs#index'

  match 'ibtrs/search' => 'ibtrs#search'
  resources :titles, :authors, :ibtrs, :branch, :stock, :stockitems
  
  match 'statistics/:title_id' => 'statistics#view'
  

  

  root :to => "Dashboard#show"

end

app/models/stockitem.rb
class Stockitem < ActiveRecord::Base
  has_one :title
  has_one :publisher
  has_one :author
  has_one :category
  
  validates :title_id, :numericality => true, :presence => true, :uniqueness => true
  validates :author_id, :numericality => true, :presence => true
  validates :category_id, :numericality => true, :presence => true
  validates :publisher_id, :numericality => true, :presence => true
  validates :title_name, :presence => true, :length => { :minimum => 1, :maximum => 100 }
  validates :isbn, :presence => true, :length => { :minimum => 10, :maximum => 16 }
  validates :language, :presence => true, :length => { :minimum => 1, :maximum => 13 }
  validates :edition, :presence => true, :length => { :minimum => 1, :maximum => 13 }
  validates :pubyear, :presence => true, :numericality => true, :length => {:minimum => 4, :maximum => 4}
  validates :pages, :presence => true, :numericality => true, :inclusion => (1..10000)
  
  validates_associated :title
  
  def self.new_for_title(titleId)
    title = Title.find(titleId)
    stockitem = Stockitem.new
    stockitem.title_id = title.id
    stockitem.author_id = title.author_id
    stockitem.category_id = title.category_id
    stockitem.publisher_id = title.publisher_id
    stockitem.title_name = title.title
    stockitem.isbn = title.isbn13
    stockitem.language = title.language
    stockitem.edition = title.edition
    stockitem.pubyear = title.yearofpublication
    stockitem.pages = title.noofpages

    stockitem.author = title.author
    
    stockitem
  end
end

app/controllers/stockitems_controller.rb
class StockitemsController < ApplicationController
  def index
    @stockitems = Stockitem.find_all_by_title_id(params[:title_id])
  end
  
  def new
    @stockitem = Stockitem.new_for_title(params[:title_id])
  end
  
  def create      
    @stockitem = Stockitem.new(params[:stockitem])
    if @stockitem.save
      redirect_to(@stockitem, :notice => 'Stockitem was successfully created')
    else
      @stockitem.author = Author.find(params[:stockitem][:author_id])
      render :action => 'new'
    end
  end
  
  def show
    @stockitem = Stockitem.find(params[:id])
  end
  
  def update
    @stockitem = Stockitem.find(params[:id])
    @stockitem.update_attributes(params[:book])
  end
end

app/helpers/stockitems_helper.rb
module StockitemsHelper
end

app/views/stockitems/_stockitem.html.erb
<%= _stockitem.id %>
<%= _stockitem.publisher_name %>
<%= _stockitem.author_name %>

<%= _stockitem.title_id %>

app/views/stockitems/index.html.erb
<h1>Listing StockItems</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @stockitems.each do |stockitem| %>
  <tr>
    <td><%= link_to 'Show', stockitem %></td>
    <td><%= link_to 'Edit', edit_stockitem_path(stockitem) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Stock Item', new_stockitem_path %>

app/views/stockitems/new.html.erb
<div class="span-13">
	<div class="span-13 push-2">
		<span>
			The information shown below comes from our titles table. 
			<br/>
			Please fill in all the information accurately, this will update titles and stocklist information.
		</span>
	</div>
	<%= form_for(@stockitem) do |f| -%>
		<% if @stockitem.errors.any? %>
		  <div id="error_explanation">
		    <h2><%= pluralize(@stockitem.errors.count, "error") %> prohibited this stockitem from being saved:</h2>

		    <ul>
		    <% @stockitem.errors.full_messages.each do |msg| %>
		      <li><%= msg %></li>
		    <% end %>
		    </ul>
		  </div>
		<% end %>

		<div class="span-3">
			<%= f.label 'Title', :style => 'float:right' %><br/>
			<%= f.label 'Author', :style => 'float:right' %><br/>
			<%= f.label 'ISBN', :style => 'float:right' %><br/>
			<%= f.label 'Price (Rupees)', :style => 'float:right' %><br/>
			<%= f.label 'Language', :style => 'float:right' %><br/>
			<%= f.label 'Edition', :style => 'float:right' %><br/>
			<%= f.label 'Published', :style => 'float:right' %><br/>
			<%= f.label 'Pages', :style => 'float:right' %><br/>
			<%= f.label 'Binding', :style => 'float:right' %><br/>
			
			<%= f.label 'Publisher', :style => 'float:right' %><br/><br/>
			<%= f.label 'Category', :style => 'float:right' %><br/>

		</div>
		<div class="span-5">
			<%= f.hidden_field :title_id %>
			<%= f.hidden_field :author_id %>
			<%= f.text_field :title_name, :size => 50, :style => 'margin:0;padding:0;' %>
			<%= fields_for @stockitem.author do |a| -%>
				<div class="span-8"><%= a.text_field :name, :disabled => true, :style => 'margin:0;padding:0' %><%= link_to 'Search', authors_path, :remote => true %></div>
			<% end -%>
			<%= f.number_field :isbn, :size => 15, :style => 'margin:0;padding:0;height:1em' %>
			<%= f.number_field :price, :size => 15, :style => 'margin:0;padding:0;height:1em' %>
			<%= f.text_field :language, :size => 15, :style => 'margin:0;padding:0' %>
			<%= f.text_field :edition, :size => 15, :style => 'margin:0;padding:0' %>
			<%= f.number_field :pubyear, :size => 5, :style => 'margin:0;padding:0' %><br/>
			<%= f.number_field :pages, :size => 5, :style => 'margin:0;padding:0' %><br/>
			<%= f.text_field :binding, :size => 10, :style => 'margin:0;padding:0' %>
			<%= f.collection_select :publisher_id, Publisher.find(:all, :order => 'name'), :id, :name, :style => 'margin:0;padding:0;border-width:10px;' %>
			<%= f.collection_select :category_id, Category.find(:all, :order => 'name'), :id, :name, :style => 'margin:0;padding:10em;' %>
		</div>
		
		<div class="span-13">
		  <%= f.submit %>
		</div>
	<% end -%>
	<br/>
	<br/>
	<div class="span-18" id="authorSearch" style="display:none;border:solid">
		<h3> Search Authors </h3>
		<%= form_tag authors_path, :method => 'get', :remote => 'true' do -%>
				<p>
					<%= text_field_tag :search, params[:search] %>
					<%= submit_tag "Search", :name => nil%>
				</p>
			<div id="authors"></div>
		<% end -%>
	</div>
	<div class="span-18" id="authorPanel" style="display:none;border:solid">
	</div>	
</div>

app/views/stockitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<b>Name:</b>
	<%= @stockitem.title_name %>
</p>

<link_to 'Edit', edit_item_path(@stockitem) %>