config/routes.rb
Opac::Application.routes.draw do

  resources :signups

  resources :plans
  
  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'

  get "stock/show"

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}
  resources :authentications

  match '/auth/failure' => 'Ibtrs#index'

  match 'ibtrs/search' => 'ibtrs#search'
  resources :titles, :authors, :ibtrs, :branch, :stock, :stockitems
  
  match 'statistics/:title_id' => 'statistics#view'
  

  

  root :to => "Dashboard#show"

end

app/models/title.rb
class Title < ActiveRecord::Base  
  belongs_to :publisher
  belongs_to :author
  belongs_to :category
  
  attr_accessible :title, :yearofpublication, :edition, :isbn10, :isbn13, :noofpages, :language 
  
  validates :title, :presence => true
  
  searchable do
    text :title, :stored => true, :more_like_this => true
    text :author, :stored => true, :more_like_this => true do
      author.name
    end
    text :category, :stored => true, :more_like_this => true do
      category.name
    end
    text :publisher, :stored => true, :more_like_this => true do
      publisher.name
    end
    integer :id, :stored => true
    integer :category_id, :references => Category, :stored => true
    integer :publisher_id, :references => Publisher, :stored => true
    integer :author_id, :references => Author, :stored => true
  end   
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  def index
    newSearch = Sunspot.new_search(Title) do
      paginate(:page => params[:page], :per_page => 15)
      facet(:category_id, :publisher_id, :author_id)
    end
    
    if !params[:queryTitleId].blank?
      if Title.exists?(params[:queryTitleId])
        @title = Title.find(params[:queryTitleId])
        if params[:query].blank?
          params[:query] = @title.title
        else
          params[:queryTitleId] = ""
        end
      end
    end
    
#    newSearch = Sunspot.new_search(Title) do
#      keywords params[:query] do
#        highlight :title, :publisher, :author
#      end
#      paginate(:page => params[:page], :per_page => 15)
#      facet(:category_id, :publisher_id, :author_id)
#    end
 
    newSearch.build do
      keywords params[:query] do
        highlight :title, :publisher, :author
      end
    end
    
    newSearch.build do 
      with(:category_id, params[:facetCategory]) 
    end if params[:facetCategory].to_i > 0

    newSearch.build do 
      with(:publisher_id, params[:facetPublisher]) 
    end if params[:facetPublisher].to_i > 0

    newSearch.build do 
      with(:author_id, params[:facetAuthor]) 
    end if params[:facetAuthor].to_i > 0
  
    @searchResults = newSearch.execute
  end

# not using more like this- not sure how this is working as of now
  def show
    @title = Title.find(params[:id])

    newSearch = Sunspot.new_more_like_this(@title, Title) do
      paginate(:page => params[:page], :per_page => 15)
      facet(:category_id, :publisher_id, :author_id)
    end
  
    newSearch.build do 
      with(:category_id, params[:facetCategory]) 
    end if params[:facetCategory].to_i > 0

    newSearch.build do 
      with(:publisher_id, params[:facetPublisher]) 
    end if params[:facetPublisher].to_i > 0

    newSearch.build do 
      with(:author_id, params[:facetAuthor]) 
    end if params[:facetAuthor].to_i > 0
  
    @searchResults = newSearch.execute

#    @searchResults = Sunspot.more_like_this(@title, Title) do
#      fields :title, :publisher, :author
#      paginate(:page => params[:page], :per_page => 15)
#      facet(:category_id, :publisher_id, :author_id)
#    end
  end
end

app/helpers/titles_helper.rb
module TitlesHelper
  def titlecount
    100000
  end
  def bookcount
    250000
  end
  def membercount
    30000
  end
  def librarycount
    30
  end
end

app/views/titles/_matchingtitles.html.erb
<div style="margin-top:20px;height:80px;width:500px;border-width:2px;border-color:black;border-style:dotted">
	<%= title_id %>..<%= @alt %>
</div>

app/views/titles/_searchresults.html.erb
<div class="facets" style="background-color:lightblue">
  <span style='float:right'>
	  <h3>Browse by Category</h3>
	  <ul class="facet">
	    <% for row in @search.facet(:category_id).rows -%>
	      <li><%= link_to(row.instance.name, url_for(:category_id => row.value)) %> (<%= row.count %>)</li>
	    <% end -%>
	  </ul>
  </span>
  <span >
	  <h3>Browse by Publisher</h3>
	  <ul class="facet">
	    <% for row in @search.facet(:publisher_id).rows -%>
	      <li><%= link_to(row.instance.name, publisher_path(row.value)) %> (<%= row.count %>)</li>
	    <% end -%>
	  </ul>
  </span>
  <span >
	  <h3>Browse by Author</h3>
	  <ul class="facet">
	    <% for row in @search.facet(:author_id).rows -%>
	      <li><%= link_to(row.instance.name, url_for(:author_id => row.value)) %> (<%= row.count %>)</li>
	    <% end -%>
	  </ul>
  </span>
</div>

<%= will_paginate @search.results %>

<div class="results" style="background-color:yellow">
  <% @search.each_hit_with_result do |hit, result| -%>
    <div class="result">
      <h3><%= link_to(hit.stored(:title), title_path(result)) %></h2>
      <div class="score"><%= hit.score %></div>
      <p><%= (hit.stored(:publisher)) %></p>
      <p><%= (hit.stored(:author)) %></p>
      <p><%= (hit.stored(:category)) %></p>
	  <p class="summary"><%= hit.highlights.first.format { |p| "<strong style='color:red'>#{p}</strong>" }.html_safe if hit.highlights.length > 0 %></p>
    </div>
  <% end -%>
</div>

app/views/titles/_title.html.erb
<tr>
  <td class="title">
    <span class="title"><%= title.title %></span>
  </td>
</tr>
<tr>
  <td class="title">
  	<span class="author"><%= title.author.name %></span>
  </td>  
</tr>
<tr>
  <td class="title">
  	<span class="language"><%= title.language %></span>
  </td>
</tr>
<tr>
  <td class="title">
  	<span class="language"><%= title.category.name %></span>
  </td>
</tr>
<tr>
  <td class="title">
  	<span class="language"><%= title.publisher.name %></span>
  </td>

</tr>

app/views/titles/index.html.erb
<div class="span-24 last">
	<%= form_tag titles_path, :id => 'searchForm', :method => 'get' do -%>
			<%= field_set_tag 'Search' do %>		
			<span>You can search by entering any text or by a specific title id or a book number.
				In case of a text search, results will including matching titles, authors and publishers.
				<br/>
				You can refine your search (limit results) by choosing a category, publisher or author.
			</span>
			<br/>
			<%= label_tag 'Title Id'%>
			<%= text_field_tag :queryTitleId, params[:queryTitleId] %>
			<br/>
			<%= label_tag 'Keywords'%>
			<%= text_field_tag :query, params[:query], :size => 100 %>
			<%= submit_tag "Submit", :name => nil %>
			<%= hidden_field_tag :facetCategory, params[:facetCategory] %>
			<%= hidden_field_tag :facetPublisher, params[:facetPublisher] %>
			<%= hidden_field_tag :facetAuthor, params[:facetAuthor] %>
			<% end -%>
	<% end -%>
</div>
<div class="span-4 colborder">
	<h4 class="alt"> Refine by Category </h4>
	  <ol class="facet">
	    <% for row in @searchResults.facet(:category_id).rows -%>
	      <li>
					<%= link_to_function(row.instance.name) do |page|
						page[:facetCategory].value = row.value;
						page[:searchForm].submit();
					end -%> 
					(<%= row.count %>)
					<%= button_to_function('X') do |page| 
						page[:facetCategory].value = nil;
						page[:searchForm].submit();						
					end if params[:facetCategory].to_i > 0 -%></li>
	    <% end -%>
	  </ol>
</div>
<div class="span-4 colborder">
  <h4 class="alt">Refine by Publisher</h4>
  <ol class="facet">
    <% for row in @searchResults.facet(:publisher_id).rows -%>
    <li>
			<%= link_to_function(row.instance.name) do |page|
				page[:facetPublisher].value = row.value;
				page[:searchForm].submit();
			end -%> 
			(<%= row.count %>)
			<%= button_to_function('X') do |page| 
				page[:facetPublisher].value = nil;
				page[:searchForm].submit();						
			end if params[:facetPublisher].to_i > 0 -%></li>
    <% end -%>
  </ol>
</div>
<div class="span-4 colborder">
  <h4 class="alt">Refine by Author</h4>
  <ol class="facet">
    <% for row in @searchResults.facet(:author_id).rows -%>
    <li>
			<%= link_to_function(row.instance.name) do |page|
				page[:facetAuthor].value = row.value;
				page[:searchForm].submit();
			end -%> 
			(<%= row.count %>)
			<%= button_to_function('X') do |page| 
				page[:facetAuthor].value = nil;
				page[:searchForm].submit();						
			end if params[:facetAuthor].to_i > 0 -%></li>
    <% end -%>
  </ol>
</div>
<div class="span-8 last">
  <h4 class="alt">Results (<%= @searchResults.total %>)</h4>
	<%= will_paginate @searchResults.results %>
	<br/>
	<hr/>
	  <% @searchResults.each_hit_with_result do |hit, result| -%>
	    <div class="box">
	      <p class="large"><%= hit.stored(:title) %></p>
		    <p>Title: <%= result.id %></p>
	      <p>Publisher: <%= (hit.stored(:publisher)) %></p>
	      <p>Author: <%= (hit.stored(:author)) %></p>
	      <p>Category: <%= hit.stored(:category) %></p>
		  <p class="summary"><%= hit.highlights.first.format { |p| "<strong style='color:red'>#{p}</strong>" }.html_safe if hit.highlights.length > 0 %></p>
	    </div>
	  <% end -%>
	</div>
</div>

app/views/titles/show.html.erb
<table class="titles" summary="Titles">
	<%= render @title %>
</table>

<%= form_tag title_path, :method => 'get' do -%>
	<p>
		<%= submit_tag "Show More Like", :name => nil %>
		<%= hidden_field_tag "mlt", :true %>
	</p>
<% end -%>

<% if @search -%>
<%= render :partial => 'searchresults' %>
<% end -%>