config/routes.rb
Opac::Application.routes.draw do

  resources :signups

  resources :plans
  
  match '/dashboard' => 'dashboard#show'

  match '/auth/:provider/callback' => 'authentications#create'

  get "stock/show"

  devise_for :users, :path => 'accounts', :controllers => {:registrations => 'registrations'}
  resources :authentications

  match '/auth/failure' => 'Ibtrs#index'

  match 'ibtrs/search' => 'ibtrs#search'
  resources :titles, :authors, :ibtrs, :branch, :stock, :stockitems
  
  match 'statistics/:title_id' => 'statistics#view'
  

  

  root :to => "Dashboard#show"

end

app/models/ibtr.rb
class Ibtr < ActiveRecord::Base
  include ActiveRecord::Transitions
  
  acts_as_versioned
  
  belongs_to :title
  belongs_to :membership
  
  belongs_to :branch
  belongs_to :respondent, :class_name => 'Branch', :foreign_key => 'respondent_id'

  attr_reader :event
  cattr_reader :per_page
  @@per_page = 10

  state_machine do
    state :New # first one is the initial state
    state :Assigned
    state :Declined
    state :Fulfilled
    state :Dispatched
    state :Received
    state :Cancelled
    
    event :assign do
      transitions :to => :Assigned, :from => [:New, :Declined, :Cancelled]
    end
    event :decline do
      transitions :to => :Declined, :from => :Assigned
    end
    event :fulfill do
      transitions :to => :Fulfilled, :from => :Assigned
    end
    event :dispatch do
      transitions :to => :Dispatched, :from => :Fulfilled
    end
    event :receive do
      transitions :to => :Received, :from => :Dispatched
    end
    event :cancel do
      transitions :to => :Cancelled, :from => [:New, :Assigned, :Declined]
    end
  end
  
  def processEvent(event)
    case 
    when event.eql?('assign') then assign
    when event.eql?('decline') then decline
    when event.eql?('fulfill') then fulfill
    when event.eql?('dispatch') then dispatch
    when event.eql?('receive') then receive
    when event.eql?('cancel') then cancel
    end
  end

  def self.search(params)
    unless (params[:card_id].nil?) then
      paginate :page => params[:page], :conditions => ['card_id = ?', params[:card_id]], :order => 'created_at, id DESC'
    else
      unless (params[:member_id].nil?) then
        paginate :page => params[:page], :conditions => ['member_id = ?', params[:member_id]], :order => 'created_at, id DESC'
      else
        unless (params[:state].nil?) then
          paginate :page => params[:page], :conditions => ['state = ?', params[:state]], :order => 'created_at, id DESC'
        else
          paginate :page => params[:page], :order => 'created_at, id DESC'
        end
      end
    end
  end  
  
  def self.complexSearch(params)
    clause = ''
    states = []

    states << params[:New] unless params[:New].nil?
    states << params[:Assigned] unless params[:Assigned].nil?
    states << params[:Cancelled] unless params[:Cancelled].nil?
    states << params[:Fulfilled] unless params[:Fulfilled].nil?
    states << params[:Declined] unless params[:Declined].nil?

    
    case 
      when params[:searchBy].eql?("card_id")
        clause << ' card_id = ?'
        values = params[:searchText]
      when params[:searchBy].eql?("member_id") 
        clause << ' member_id = ?'
        values = params[:searchText]
      when params[:searchBy].eql?("title_id") 
        clause << ' title_id = ?'
        values = params[:searchText]
      when params[:searchBy].eql?("branch_id") 
        clause << ' branch_id = ?'
        values = params[:branchVal]
      when params[:searchBy].eql?("respondent_id")
        clause << ' respondent_id = ?'
        values = params[:branchVal]
    end

    if !values.nil? && values.length > 0 then
      if states.length > 0 then
        paginate :page => params[:page], :conditions => [clause << ' AND state IN (?)', values, states], :order => 'created_at, id DESC'
      else
        paginate :page => params[:page], :conditions => [clause, values], :order => 'created_at, id DESC'
      end
    else
      paginate :page => params[:page], :conditions => ['state in (?)', states], :order => 'created_at, id DESC'
    end
  end  
end

app/controllers/ibtrs_controller.rb
class IbtrsController < ApplicationController
  def index
    @ibtrs = Ibtr.search(params)
  end
  
  def update
    @ibtr = Ibtr.find(params[:id])
    @ibtr.processEvent(params[:ibtr][:event])
    @ibtr.update_attributes(:respondent_id => params[:ibtr][:respondent_id], 
                            :reason_id => params[:ibtr][:reason_id], 
                            :comments => params[:ibtr][:comments], 
                            :state => @ibtr.current_state)
    flash[:notice] = "Successfully #{@ibtr.state} " << (params[:ibtr][:event].eql?("assign") ? "to #{@ibtr.respondent_id}!" : "!")
  rescue Transitions::InvalidTransition
    flash[:error] = "Cannot #{params[:ibtr][:event]} a request that is #{@ibtr.state}."
  end  
  
  def search
    @ibtrs = Ibtr.complexSearch(params)
  end
end

app/helpers/ibtr_helper.rb
module IbtrHelper  
  def image_url(titleId)
    if titleId then
      "http://justbooksclc.com/images/titles/#{titleId}.jpg"
    else
      "#"
    end
  end
  
  def action_buttons(state, edit_id, edit_event_id)
    buttons = ""
    actions = []
    case 
    when state.eql?("New") then actions << "Assign" << "Cancel"
    when state.eql?("Declined") then actions << "Assign" << "Cancel"
    when state.eql?("Assigned") then actions << "Decline" << "Fulfill" << "Cancel"
    when state.eql?("Fulfilled") then actions << "Dispatch"
    when state.eql?("Dispatched") then actions << "Receive"
    end
    
    actions.sort!
    
    actions.each { |action|
        buttons << button_to_function(action, "$('#{edit_id} #{edit_event_id}').val('#{action.downcase}');$('#{edit_id}').submit()", :class => ".ibtr_#{action.downcase}" )
    }
    buttons
  end
  
end

app/views/ibtrs/_alternate.html.erb
<h4>Coming Soon...</h4>


<%= link_to_function "Go Back...", "IBTapp.showPanel(#{ibtr.id}, 'div_req_#{ibtr.id}')" %>

app/views/ibtrs/_assign.html.erb
<div class="span-13", id = <%= "stock_#{ibtr.id}" %> >
	<h6>Current Stock Position</h6>
	<%= render :partial => '/statistics/view', :locals => { :counter => ibtr.id, :title_id => ibtr.title_id } %>
	<br/>
</div>
<div class="span-13">
		Green represents available stock, Blue represents in circulation, Red means unavailable.
		<br/>
		<br/>
		If there are no stocks, then you may decide to either
		<%= link_to_function "cancel", "IBTapp.showPanel(#{ibtr.id}, 'div_can_#{ibtr.id}')" %> the request, proceed for 
		<%= link_to_function "procurement.", "IBTapp.showPanel(#{ibtr.id}, 'div_pro_#{ibtr.id}')" %> or
		choose an <%= link_to_function "alternate title.", "IBTapp.showPanel(#{ibtr.id}, 'div_alt_#{ibtr.id}')" %>
</div>
<div class="span-13">
<%= form_for ibtr, :remote => :true, :html => {:autocomplete => :off}  do |f| -%>
	<%= f.hidden_field :event, :value => 'assign' %>
	<%= f.label :respondent_id %> <%= f.collection_select(:respondent_id, Branch.all, :id, :name) %>
	<br/>
	<%= f.label :comments %> <%= f.text_field :comments, :class => 'comment', :placeholder => 'Enter a comment' %>
	<br/>
	<%= f.submit 'Assign'%>
<% end -%>
<br/>
<%= link_to_function "Go Back...", "IBTapp.showPanel(#{ibtr.id}, 'div_req_#{ibtr.id}')" %>
</div>

app/views/ibtrs/_cancel.html.erb
<div class="span-13">
<%= form_for ibtr, :remote => :true, :html => {:autocomplete => :off}  do |f| -%>
	<%= f.hidden_field :event, :value => 'cancel' %>
	<%= f.label :reason_id %> <%= f.select(:reason_id, [['Available in Home Branch', 1], ['Not Available in Any Branch', 2], ['Please Request Extra Copies', 3], ['Please Recommend Procurement', 4], ['Duplicate Request', 5]]) %>
	<br/>
	<%= f.label :comments %> <%= f.text_field :comments, :class => 'comment', :placeholder => 'Enter a comment' %>
	<br/>
	<%= f.submit 'Cancel'%>	
<% end -%>
<br/>
<%= link_to_function "Go Back...", "IBTapp.showPanel(#{ibtr.id}, 'div_req_#{ibtr.id}')" %>
</div>

app/views/ibtrs/_ibtr.html.erb
<div class="span-14">
	<div class="span-14">	
		<div class="span-5">
			<h4><%= "#{ibtr.state} Request: #{ibtr.id}" %></h4>
		</div>
		<div class="span-8">
			<h5 style="float:right"><%= distance_of_time_in_words(ibtr.created_at, Time.now) %> ago</h5>
		</div>
	</div>
	<div id = "<%= "flash_#{ibtr.id}" %>" class="span-8">
	</div>
	<div id = "<%= "div_#{ibtr.id}" %>" class="span-14">
		<div class="span-13">

			<div class="span-11" id = "<%= "div_req_#{ibtr.id}" %>">
				<%= render :partial => 'request', :locals => { :ibtr => ibtr } %>
			</div>

			<div class="span-11" id = "<%= "div_ass_#{ibtr.id}" %>" style="display:none">
				<%= render :partial => 'assign', :locals => { :ibtr => ibtr } %>
			</div>

			<div class="span-11" id = "<%= "div_alt_#{ibtr.id}" %>" style="display:none">
				<%= render :partial => 'alternate', :locals => { :ibtr => ibtr } %>
			</div>

			<div class="span-11" id = "<%= "div_can_#{ibtr.id}" %>" style="display:none">
				<%= render :partial => 'cancel', :locals => { :ibtr => ibtr } %>
			</div>

			<div class="span-11" id = "<%= "div_pro_#{ibtr.id}" %>" style="display:none">
				<%= render :partial => 'procure', :locals => { :ibtr => ibtr } %>
			</div>

			<div class="span-1 push-1">
				<%= image_tag image_url(ibtr.title_id), :size => "100x150", :alt => 'No Image', :id => "img_#{ibtr.id}" %>
			</div>

			<br/>
		</div>
		<div class="span-13" style="margin-top:10px;display:none">
			<%= link_to_function "Show History", "", :id => "toggle_history_#{ibtr.id}", :class => "toggle_history"%>
			(<%= ibtr.versions.length %>)
			<%= link_to_function "Hide Stock", "", :id => "toggle_stock_#{ibtr.id}", :class => "toggle_stock"%>			
		</div>
		<div id=<%= "history_#{ibtr.id}" %> class="span-13 scroll-pane" style="height:160px;overflow-y:scroll;display:none">
			<table summary="History" border="0" cellspacing="0" cellpadding="0">
				<tr>
					<th>#</th>
					<th>Title</th>
					<th colspan="3">Event</th>
				</tr>
				<%= render :partial => 'ibtrversion', :collection => ibtr.versions.reverse %>
			</table>
		</div>
		<div class="span-13;" style="display:none">
			<%= form_tag('/stock/show', :id => "alt_#{ibtr.id}", :method=>'get', :remote => true, :autocomplete => :off) do -%>
				<%= label_tag :title_id, 'Alternate Title Id' %>
				<%= text_field_tag :title_id, params[:title_id], :onchange => "$('#alt_#{ibtr.id}').submit();", :size => 15  %>
				<%= text_field_tag "title_#{ibtr.id}", params[:title_name], :disabled => true, :size => 30  %>
				<%= hidden_field_tag :result, params[:result], :value => "#{ibtr.id}" %>
			<% end -%>
		</div>

	</div>
</div>
<br/>

app/views/ibtrs/_ibtr_spacer.html.erb
<div class="span-14 spacer">
</div>

app/views/ibtrs/_ibtrversion.html.erb
<tr>
<td><%= ibtrversion.version %></td>
<td><%= ibtrversion.title_id  %></td>
<td><%= ibtrversion.state %></td>
<td>
<%=
	case 
	when ibtrversion.state.eql?('Assigned') then 'to'
	when ibtrversion.state.eql?('Declined') then 'by'
	when ibtrversion.state.eql?('Fulfilled') then 'by'
	when ibtrversion.state.eql?('Dispatched') then 'by'
	when ibtrversion.state.eql?('Received') then 'by'
	when ibtrversion.state.eql?('Cancelled')
	end
%>
</td>
<td><%= ibtrversion.respondent_id unless ibtrversion.state.eql?('Cancelled') %></td>
<td><%= distance_of_time_in_words(ibtrversion.updated_at, Time.now) %> ago</td>
</tr>

app/views/ibtrs/_procure.html.erb
<%= content_tag :div, :class => 'span-13' do -%>
	Coming soon...

]		
<% end -%>

<%= link_to_function "Go Back...", "IBTapp.showPanel(#{ibtr.id}, 'div_req_#{ibtr.id}')" %>

app/views/ibtrs/_request.html.erb
Member <%= link_to "#{ibtr.member_id}", ibtrs_path(:member_id => "#{ibtr.member_id}") %>,
with card <%= link_to "#{ibtr.card_id}", ibtrs_path(:card_id => "#{ibtr.card_id}") %>
has requested for
	#<%= link_to_function ibtr.title_id, "$('#alt_#{ibtr.id} input#title_id').val(#{ibtr.title_id});$('#alt_#{ibtr.id}').submit();" %>:
<% unless ibtr.title.nil? -%>
	<%= link_to ibtr.title.title, '#' %> 
<% end -%>
<br/>
via
#<%= ibtr.branch_id %>:
<% unless ibtr.branch.nil? -%>
	<%= link_to ibtr.branch.name, '#' %> 
<% end -%>.
<div class="span-13">
		<br/>
		See stock position to decide which branch this request should be 
		<%= link_to_function "assigned.", "IBTapp.showPanel(#{ibtr.id}, 'div_ass_#{ibtr.id}')" %>
		<br/>
		If there are no stocks, then you may decide to either
		<%= link_to_function "cancel", "IBTapp.showPanel(#{ibtr.id}, 'div_can_#{ibtr.id}')" %> the request, proceed for 
		<%= link_to_function "procurement.", "IBTapp.showPanel(#{ibtr.id}, 'div_pro_#{ibtr.id}')" %> or
		choose an <%= link_to_function "alternate title.", "IBTapp.showPanel(#{ibtr.id}, 'div_alt_#{ibtr.id}')" %>
</div>

app/views/ibtrs/_searchResult.html.erb
<%= content_tag :div, :class=> "span-24", :id => "div_#{searchResult.id}" do -%>
	<div class="span-1"><%= searchResult_counter + 1 %></div>
	<div class="span-5"><%= searchResult.created_at.strftime('%d-%b-%y') %>
											(<%= distance_of_time_in_words(searchResult.created_at, Time.now) %> ago)<br/></div>
	<div class="span-2"><%= searchResult.member_id %><br/></div>
	<div class="span-2"><%= searchResult.card_id %><br/></div>
	<div class="span-2"><%= searchResult.branch_id %><br/></div>
	<div class="span-2"><%= searchResult.state %><br/></div>
	<div class="span-2"><%= searchResult.respondent_id %><br/></div>
	<div class="span-5"><%= searchResult.updated_at.strftime('%d-%b-%y') %>
											(<%= distance_of_time_in_words(searchResult.updated_at, Time.now) %> ago)<br/></div>
	<div class="span-2"><%= link_to(searchResult.versions.count, '#') %><br/></div>
<% end -%>

app/views/ibtrs/index.html.erb
<div class="span-4 colborder">
	<div class="span-4">
		<p></p>
		<p><%= link_to "New Requests", ibtrs_path(:state => 'New') %> </p>
		<p><%= link_to "Assigned Requests", ibtrs_path(:state => 'Assigned') %> </p>
		<p><%= link_to "Declined Requests", ibtrs_path(:state => 'Declined') %> </p>
		<p><%= link_to "Fulfilled Requests", ibtrs_path(:state => 'Fulfilled') %> </p>
		<p><%= link_to "Cancelled Requests", ibtrs_path(:state => 'Cancelled') %> </p>
		<p><%= link_to "Dispatched Requests", ibtrs_path(:state => 'Dispatched') %> </p>
		<p><%= link_to "Received Requests", ibtrs_path(:state => 'Received') %> </p>
		<p><%= link_to "All Requests", ibtrs_path %>	</p>
	</div>
	<hr/>
	<div class="span-4">
		<p></p>
		<p><%= link_to "Search", ibtrs_search_path %>	</p>
	</div>	
</div>

<div class="span-14">
	<h4><%= "Showing All #{params[:state]} Requests" %><%= " for #{params[:card_id]}" unless params[:card_id].nil? %> (<%= @ibtrs.total_entries %>)</h4>
	<br/>
	<%= will_paginate(@ibtrs) %>
	<hr/>
	<%= render :partial => "ibtr", :collection => @ibtrs, :spacer_template => "ibtr_spacer" %>
</div>

app/views/ibtrs/search.html.erb
<%= javascript_tag :defer => 'defer' do -%>
	$(document).ready(function () {
		IBTapp.initSearchForm('<%= params[:searchBy] %>', true);
	});
<% end -%>
<div class="span-24">
	<%= form_tag ibtrs_search_path, :class=>'ibtrSearch', :method => 'get' do -%>
			<%= field_set_tag 'Search' do %>
				<%= label_tag 'Search By:'%>
				<%= select_tag :searchBy, options_for_select([['Card',:card_id],['Member',:member_id],['Title',:title_id],['Requesting Branch',:branch_id],['Respondent Branch',:respondent_id]], params[:searchBy]) %>
				<%= text_field_tag :searchText, params[:searchText] %>
				<%= select_tag :branchVal, options_from_collection_for_select(Branch.all, :id, :name, params[:branchVal]) %>
				<br/>
				<br/>
				<%= label_tag :New %>
				<%= check_box_tag :New,:New,params[:New] %>
				<%= label_tag :Assigned %>
				<%= check_box_tag :Assigned,:Assigned,params[:Assigned] %>
				<%= label_tag :Cancelled %>
				<%= check_box_tag :Cancelled,:Cancelled,params[:Cancelled] %>
				<%= label_tag :Fulfilled %>
				<%= check_box_tag :Fulfilled,:Fulfilled,params[:Fulfilled] %>
				<%= label_tag :Declined %>
				<%= check_box_tag :Declined,:Declined,params[:Declined] %>

				<%= submit_tag "Submit", :name => nil %>
			<% end -%>
	<% end -%>
</div>

<div class="span-24">
	<h4><%= "Total Results: #{@ibtrs.total_entries} " if defined?(@ibtrs) %></h4>
	<%= will_paginate(@ibtrs) if defined?(@ibtrs) %>
	<hr/>
	<div class="span-24">
		<div class="span-1"><br/></div>
		<div class="span-5"><h6>Created At</h6></div>
		<div class="span-2"><h6>Member</h6></div>
		<div class="span-2"><h6>Card</h6></div>
		<div class="span-2"><h6>Via</h6></div>
		<div class="span-2"><h6>State</h6></div>
		<div class="span-2"><h6>Respondent</h6></div>
		<div class="span-5"><h6>Last Updated</h6></div>
		<div class="span-2"><h6>History</h6></div>
	</div>	
	<%= render :partial => "searchResult", :collection => @ibtrs %>
</div>

app/views/ibtrs/update.js.erb
$('<%= "#flash_#{params[:id]}" %>').html('<%= escape_javascript(render(:partial => 'layouts/flash', :locals => {:flash => flash, :flush_flash => true})) %>');

<% if defined?(@ibtr) -%> 
	$('<%= "#edit_ibtr_#{params[:id]} input#ibtr_state" %>').val('<%= @ibtr.state %>');
	$('<%= "#edit_ibtr_#{params[:id]} input#ibtr_respondent_id" %>').val('<%= @ibtr.respondent_id %>');
<% end -%>

<% if defined?(@ibtr.respondent.name) -%>
	$('<%= "#edit_ibtr_#{params[:id]} a#ibtr_respondent_name" %>').html('<%= @ibtr.respondent.name %>');
<% end -%>